@endpoint = https://f8ur0iz1oc.execute-api.eu-west-2.amazonaws.com/prod/
GET {{endpoint}}/hello/
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "Location": "London",
    "name": "Best Location"
}
###